### PR TITLE
Add link to GitHub in footer

### PR DESCRIPTION
**Pull request by NickColley**
Should make it easier for people who spot issues to find the source code for this website.

Did this on my phone so let me know if there is any issues.

### CODE REVIEW

**Comment by chrimesdev** [comment]
Just changing the target branch to `develop` to release it to the staging environment beforehand (probably needs to be documented somewhere)

But other than that code is 👍

**Comment by chrimesdev** [comment]
The branch just needs rebasing with `develop` and a change log entry under `1.0.2` if you can @nickcolley 

@edent do we need to check this with stakeholders as its a change to the approved design/content?

**Comment by edent** [comment]
@adamchrimes I hereby give you and your team autonomy to make sensible decisions.

**Review by edent — APPROVED** [review]

**Comment by bencullimore** [comment]
@nickcolley @edent 

This is a great idea - but is there a distinct user need for a github link in the footer?

My assumption would be those interested in seeing the code and contributing would already have GitHub accounts and their own means for finding repositories. Those who don't know what GitHub is would just ignore, or it may become an unwelcome distraction in the footer. 

If NHSX want to promote their website repo - could this be achieved in a different way? A blog post might give users more context? 

On top of this, the link is quite long and reduces the scalability of the other links (see desktop screenshot below)

Screenshot 2019-04-09 at 15 39 06

**Comment by NickColley** [comment]
> but is there a distinct user need for a github link in the footer

It's pretty difficult to find this repository is all, only reason I knew how to get here as because the repo name was in a screenshot. If you want to be open to contributions you need to reduce the effort required to contribute, by making people have to guess from Google they will likely just not bother even raising an issue.

Most people will not know that your website is even open source.

> On top of this, the link is quite long and reduces the scalability of the other links (see desktop screenshot below)

I'm not sure what scalability means here, the link has a very clear accessible name :)

I'll close this out for now.

**Pull request closed without merging**
