### PR TITLE
Windows high contrast mode changes

### PR DESCRIPTION
**Pull request by mcheung-nhs**
## Description
Using the (unsupported) -ms-high-contrast media query to tidy up the
homepage.

These changes are based on feedback by a visually impaired user using
high contrast mode on a Windows computer.

The person noted that where the hero image is, there is just blank space
 (high contrast mode doesn't seem to display background images) so the
 user wasn't sure if they were missing something. Therefore I suggest
 removing the background image and arrow icon in high contrast mode.

With the 'promo' boxes, it's functionality is that the whole box is a
link. When hovering over the area with a mouse, the cursor changes to a
pointer as expected. Hovering over bits where there is no text (blank
space) similarly raised the question of whether the user was missing
something. Therefore I suggest adding a border around the promo to show
the area the box covers. This can be done by adding a 1px transparent
border, which obviously has no affect when not in high contrast mode.

## Checklist

- [ ] Tested against the [NHS.UK frontend testing policy](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/testing.md) (Resolution, Browser & Accessibility)
- [ ] Code follows the [NHS.UK frontend coding standards](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/coding-standards.md)
- [ ] Documentation
- [ ] Version number increase (using [SEMVER](https://semver.org/))
- [x] CHANGELOG entry
- [ ] Validated on staging environment (only required for releases)

**Live (top)**
nhsx-high-contrast-top-live

**Live (bottom)**
nhsx-high-contrast-bottom-live

**Fix (top)**
nhsx-high-contrast-top-fix

**Fix (bottom)**
nhsx-high-contrast-bottom-fix

### CODE REVIEW

**Comment by chrimesdev** [comment]
Looks good - tested on Surface Book Windows 10.

Do we need to raise an issue on the NHS.UK frontend for this?

**Comment by mcheung-nhs** [comment]
@AdamChrimes - If you're happy to use this, then it's probably best to fix it in the NHS.UK frontend library, so it's standard for all. So no need to merge this. I'll close this when  that gets done.

**Comment by chrimesdev** [comment]
Sounds good - we could probably include it in version `2.1.0` that is waiting to be released.

**Comment by chrimesdev** [comment]
This was fixed in [version 2.1.0](https://github.com/nhsuk/nhsuk-frontend/releases/tag/2.1.0) of the NHS.UK frontend library.

The version has been bumped in the `develop` branch and will be released within the next few days.

**Pull request closed without merging**
