### PR TITLE
Fix/accessibility

### PR DESCRIPTION
**Pull request by mcheung-nhs**
## Description
Fixing the heading structure on pages where it goes from a H1 to a H3.
Added missing title attribute on the home page video iframe.

### Related issue
None
## Checklist

- [x] Tested against the [NHS.UK frontend testing policy](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/testing.md) (Resolution, Browser & Accessibility)
- [x] Code follows the [NHS.UK frontend coding standards](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/coding-standards.md)
- [ ] Documentation
- [x] Version number increase (using [SEMVER](https://semver.org/))
- [x] CHANGELOG entry
- [ ] Validated on staging environment (only required for releases)

### CODE REVIEW

**Review by bencullimore — APPROVED** [review]
👍

**Comment by chrimesdev** [comment]
From a code point of a view, all looks good.

The typography sizing slightly changes on the 'Key information and tools' subpages, due to the `<h3>` being changed to `<h2>`. This visual change could be negated by using the modifier class `class="nhsuk-heading-m"`.

@bencullimore are you happy with the visual change or do modifier classes need to be used?

**Comment by bencullimore** [comment]
@AdamChrimes please could we have the modifier classes to make sure the text size stays the same but has the improved structure.

Ta

**Comment by chrimesdev** [comment]
@mcheung-nhs are you OK to make the changes requested by Ben? Also if you could rebase the branch with `dev` to get rid of the historic merges in this PR.

**Review by chrimesdev — APPROVED** [review]
👍 Merging into `develop` to review on the staging environment before releasing.

**Pull request merged**
